name: PyInstaller Action

on:
  push:
    branches:
      - '**'  # Trigger on any push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y libgirepository1.0-dev python3-gi

      - name: Run PyInstaller
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: baldilevelsaver.py
          requirements: requirements.txt
          options: '--windowed --onefile --clean --hidden-import=gi'
          python_ver: '3.10'
          python_arch: x64
          exe_path: ./dist
          upload_exe_with_name: baldilevelsaver.py
          
