name: PyInstaller Linux Build

on:
  push:
    branches:
      - "**"  

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - name: github actions sucks
        run: |
          echo I'm done with trying actions
