name: PyInstaller Action

on:
  push:
    branches:
      - '**'  # Trigger on any push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyInstaller
        uses: Martin005/pyinstaller-action@v1.2.0
        with:
          spec: baldilevelsaver.py  # Replace with your actual .spec or .py file path
          requirements: requirements.txt
          options: '--windowed --onefile'
          python_ver: '3.10'
          python_arch: x64
          exe_path: ./dist  # The default output path for executables
          upload_exe_with_name: baldilevelsaver  # Optional: Change this to your desired artifact name

      # Upload the executable as an artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-baldilevelsaver-artifact  # This is the name of the artifact
          path: ./dist  # Path to the output directory
