name: PyInstaller Action

# You may pin to the exact commit or the version.
# uses: Martin005/pyinstaller-action@dcfd75f8789130c10c0a34c3dee563e3f6906ea4
uses: Martin005/pyinstaller-action@v1.2.0

with:
  # path of your '.py' or '.spec' file.
  # This file will be used to create executable.
  # If .py: Generated spec file will also be uploaded as artifact
  spec: path/to/your_file.spec  # or use path/to/your_script.py for .py file

  # path of your requirements.txt file
  requirements: requirements.txt # optional, default is none

  # Options to set for pyinstaller command (separated by comma and space)
  options: '--windowed --onefile' # optional, default is none

  # specific Python version you want to use (e.g., 3.8, 3.9, etc.)
  python_ver: 3.10  # optional, default is 3.10

  # specific Python architecture you want to use (e.g., x64, x86)
  python_arch: x64  # optional, default is x64

  # Path on runner OS where generated executable files are stored
  exe_path: ./dist  # optional, default is ./dist

  # If passed, uploads executable artifact with this name
  upload_exe_with_name: my_executable_name  # optional, default is none
